spring:
  datasource:
    hikari:
      connection-timeout: 1000
      maximum-pool-size: 10
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?sslmode=disable
    username: root
    password: secret
  jpa:
    hibernate:
      ddl-auto: update


html:
  xpath:
    article: //*[@id="post-50502"]/div/div[2]/div[6]
    title: //*[@id="post-50502"]/div/div[2]/h1/b
    image: //*[@id="post-50502"]/div/div[2]/div[4]/img
    published-at: //*[@id="post-50502"]/div/div[2]/div[1]/div/time
